print("REGLAS DE MI JUEGO DE MESA FAVORITO: JENGA")
print("1. En una mesa construye los 54 bloques en una torre, colocando 3 bloques por nivel, alternando la dirección en cada nivel.")
print("2. El jugador que construyó la torre empieza el juego.")
print("3. En tu turno, retira un solo bloque de cualquier nivel por debajo del nivel más alto completo.")
print("4. Se utiliza solo una mano a la vez para retirar el bloque.")
print("5. Coloca el bloque retirado en la parte superior de la torre, formando nuevos niveles de 3 bloques.")
print("6. No puedes saltarte tu turno.")
print("7. Se continúa el juego pasando turnos en sentido de las agujas del reloj.")
print("8. El juego termina cuando la torre se cae.")
print("9. El perdedor es el jugador que hace que la torre se caiga.")
print("10. Para jugar de nuevo, se hace al perdedor reconstruir la torre o se realiza entre todo el grupo.")