print("PERSONA: ¡Mi amorrrr, ya llegué del trabajo! ¿Dónde está mi llauchita? (en una voz tan aguda que ni los perros la entienden).")
print("GATO: Tengo nombre propio, ¿sabe? No es como que yo diga: '¡Ah, una humana chillona!'")
print("PERSONA: (gritando) ¡¿ME HABLÓ EL GATO?! ¿CÓMO ES POSIBLE? ¿CÓMO TE LLAMAS?")
print("GATO: Hssssss... (le da un zarpazo y se va a esconder debajo del sofá).")
print("PERSONA: Bueno, oficialmente estoy loca... y con una herida. Tsk, tsk... solo en Bolivia.")