print(" TUTORIAL DE CÓMO LAVAR LOS PLATOS")
print("-----------------------------------------")
print()
print("MATERIALES: ")
print("1. Esponja de doble cara: una con lado suave y otro abrasivo.")
print("2. Jabón líquido para platos (preferiblemente desengrasante).")
print("3. Guantes de goma (opcional, para proteger tus manos del agua caliente).")
print("4. Agua caliente o tibia.")
print("5. Secador de platos o un paño de cocina limpio y seco.")
print("6. Lavaplatos.")
print()
print("IMPORTANTE: ")
print("    -Retira todos los restos grandes de comida y tíralos al basurero.")
print("    -Si hay restos secos o pegados, deja los platos a remojar en agua caliente y con un poco de jabón (preferiblemente en un recipiente) por 5 minutos.")
print("    -Organiza los platos por tipo: vasos y tazas, cubiertos, platos, recipiente plásticos, ollas y sartenes.")
print()
print("LAVADO: ")
print(" 1. Vasos y tazas:")
print("     1.1. Usa el lado suave de la esponja para evitar rayarlos.")
print("     1.2. Enjuágalos inmediatamente después de enjabonarlos.")
print(" 2. Cubiertos:")
print("     2.1. Frota bien entre los dientes de los tenedores y en los mangos.")
print("     2.2. Usa el lado abrasivo si hay restos secos, pero con cuidado.")
print(" 3. Platos:")
print("     3.1. Usa el lado abrasivo para manchas difíciles.")
print("     3.2. No olvides lavar también por debajo.")
print(" 4. Plásticos y tupperware:")
print("     4.1. Evita agua muy caliente si el plástico no lo permite.")
print("     4.2. Asegúrate de lavar bien las tapas.")
print(" 5. Ollas y sartenes:")
print("     5.1. Usa el lado abrasivo de la esponja con movimientos circulares.")
print("     5.2. Si hay grasa o comida pegada, remoja con agua caliente antes de fregar.")
print()
print("ENJUAGE: ")
print("1. Enjuaga con agua caliente o tibia:")
print("2. Asegúrate de eliminar todo el jabón y la grasa.")
print()
print("SECADO: ")
print("-Opción 1: Deja escurrir en un escurreplatos limpio.")
print("-Opción 2: Usa un paño de cocina limpio (preferiblemente de microfibra) para secar a mano.")
print()
print("PARA FINALIZAR: ")
print("-Enjuaga bien la esponja y exprímela. Déjala secar al aire.")
print("-Limpia el lavaplatos y alrededor para mantener todo higiénico.")
print("-Guarda los utensilios y platos secos en su lugar correspondiente.")
print()
print("-----------------------------------------")
print("FIN")